import { DateTime } from 'luxon'
import { BaseModel, column, belongsTo } from '@adonisjs/lucid/orm'
import type { BelongsTo } from '@adonisjs/lucid/types/relations'
import User from './user.js'

/**
 * Business Model
 * Represents a single business profile created by an owner during onboarding
 * Each business belongs to one owner (User)
 */
export default class Business extends BaseModel {
  // The unique ID for this business — auto generated by the database
  @column({ isPrimary: true })
  declare id: number

  // Links this business to the owner who created it
  // This matches the owner_id column in the businesses table
  @column()
  declare ownerId: number

  // The business name e.g. "Luxe Salon"
  @column()
  declare name: string

  // The type of business — only these seven are allowed
  @column()
  declare category:
    | 'Beauty & Personal Care'
    | 'Health & Fitness'
    | 'Medical & Wellness'
    | 'Pet Services'
    | 'Home Services'
    | 'Professional Services'
    | 'Tech Services'

  // Optional description the owner writes during onboarding
  @column()
  declare description: string | null

  // File path or URL to the uploaded business logo
  @column()
  declare logo: string | null

  // How bookings are confirmed:
  // 'instant' = confirmed automatically
  // 'request' = owner confirms manually
  @column()
  declare bookingPolicy: 'instant' | 'request'

  // The current account status of this business
  @column()
  declare status: 'trial' | 'active' | 'suspended'

  // When the 14-day free trial ends
  @column.dateTime()
  declare trialEndsAt: DateTime | null

  // Whether this business is visible to customers
  @column()
  declare isActive: boolean

  // Automatically set when the business is first created
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime

  // Automatically updated every time the business record changes
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime

  // Relationship — a business belongs to one owner (User)
  // This lets us do business.owner to get the owner's details
  @belongsTo(() => User)
  declare owner: BelongsTo<typeof User>
}
